Controllers/ListingController.cs
using Microsoft.AspNetCore.Mvc;
using MediaToolkit;
using NotFinal.Areas.Identity.Data;
using NotFinal.Models;
using Microsoft.EntityFrameworkCore;
using MediaToolkit.Model;

namespace NotFinal.Controllers
{
    public class ListingController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IWebHostEnvironment _env;
        public ListingController(ApplicationDbContext dbContext, IWebHostEnvironment env)
        {
            _dbContext = dbContext;
            _env = env;
        }
        public IActionResult Index()
        {
            return View();
        }
        static readonly string[] SizeSuffixes =
                  { "bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB" };
        public string Getsize(string path)
        {
            if (System.IO.File.Exists(path))
            {
                return (((new FileInfo(path).Length)/ (1024 * 1024))+" mb");
            }
            return "mb";
        }

        public async Task<ActionResult> List()
        {
            List<VideoConfig> AllVideos = new List<VideoConfig>();
            var data = await _dbContext.VideoConfigs.ToListAsync();

            foreach (var video in data)
            {
                VideoConfig model = new VideoConfig();
                var filename = video.OriginalVideo;
                var savePath = "/Upload/" + filename;
                model.Id = video.Id;
                model.OriginalVideo = savePath;
                model.Title = video.Title;
                model.CreatedBy = video.CreatedBy;
                model.CreatedDate = video.CreatedDate;
                model.Duration = video.Duration;
                AllVideos.Add(model);
            }
            return View(AllVideos);
        }
        [HttpPost]
        public async Task<ActionResult> DeleteVideoData(string Id)
        {
            var directory = Directory.GetCurrentDirectory();
            var PID = Convert.ToInt32(Id);
            var result = string.Empty;
            if (PID != 0)
            {
                var data = await _dbContext.VideoConfigs.Where(x => x.Id == PID).FirstOrDefaultAsync();
                if (data != null)
                {
                    if (data.LowQuality != null)
                    {
                        var filename = string.Empty;
                        filename = directory + "\\wwwroot\\" + data.LowQuality;
                        //var savePath = Path.Combine(_env.WebRootPath, "Converted\\", filename);

                        System.IO.File.Delete(filename);
                    }
                    if (data.MediumQuality != null)
                    {
                        var filename = string.Empty;
                        filename = directory + "\\wwwroot\\" + data.MediumQuality;
                        //var savePath = Path.Combine(_env.WebRootPath, "Converted\\", filename);
                        System.IO.File.Delete(filename);
                    }
                    if (data.HighQuality != null)
                    {
                        var filename = string.Empty;
                        filename = directory + "\\wwwroot\\" + data.HighQuality;
                        // var savePath = Path.Combine(_env.WebRootPath, "Converted\\", filename);
                        System.IO.File.Delete(filename);
                    }
                    if (data.VeryHighQuality != null)
                    {
                        var filename = string.Empty;
                        filename = directory + "\\wwwroot\\" + data.VeryHighQuality;
                        //var savePath = Path.Combine(_env.WebRootPath, "Converted\\", filename);
                        System.IO.File.Delete(filename);
                    }

                    if (data.OriginalVideo != null)
                    {
                        var filename = string.Empty;
                        filename = directory + "\\wwwroot\\Upload\\" + data.OriginalVideo;
                        //var savePath = Path.Combine(_env.WebRootPath, "Upload\\", filename);
                        System.IO.File.Delete(filename);
                    }

                    _dbContext.Remove(data);
                    await _dbContext.SaveChangesAsync();
                    result = "1";

                }
                else
                {
                    result = "0";
                }
            }
            else
            {
                result = "0";
            }

            return Json(result);
        }
        //public async Task<ActionResult> List()
        //{
        //    List<VideoConfig> AllVideos = new List<VideoConfig>();
        //    var data = await _dbContext.VideoConfigs.ToListAsync();

        //    foreach (var video in data)
        //    {
        //        VideoConfig model = new VideoConfig();
        //        var filename = video.OriginalVideo;
        //        var savePath = "/Upload/" + filename;
        //        model.OriginalVideo = savePath;
        //        model.Id= video.Id;
        //        model.Duration = video.Duration;
        //        model.CreatedDate = video.CreatedDate;
        //        model.CreatedBy = video.CreatedBy;
        //        model.Title = video.Title;
        //        AllVideos.Add(model);
        //    }
        //    return View(AllVideos);
        //}
        public async Task<ActionResult> Display(int id,int? a)
        {
            var display = fileinfo(id,a);
           // var model = _dbContext.VideoConfigs.FirstOrDefault(x=>x.Id==id);

           // Displaysingle display = new Displaysingle();
           // // File Size
           // var file =_env.WebRootPath+"\\Upload\\" + model.OriginalVideo;
           // display.Size = Getsize(file);
           // display.Duration = Timeduration(file);
           // if (a==1)
           // {
           //     file = _env.WebRootPath + "\\"+model.LowQuality;
           //     display.Resolution = "352*240";
           //     display.Size = Getsize(file);
           // }  
           //else if (a==2)
           // {
           //     file = _env.WebRootPath + "\\" + model.MediumQuality;
           //     display.Resolution = "480*360";
           //     display.Size = Getsize(file);
           // } 
           // else if (a==3)
           // {
           //     file = _env.WebRootPath + "\\" + model.HighQuality;
           //     display.Resolution = "640*480";
           //     display.Size = Getsize(file);
           // } 
           // else if (a==4)
           // {
           //     file = _env.WebRootPath + "\\" + model.VeryHighQuality;
           //     display.Resolution = "1280*720";
           //     display.Size = Getsize(file);
           // }

           
            return View(display);
        }
        [HttpPost]
        public Displaysingle fileinfo(int id, int? a)
        {
            var model = _dbContext.VideoConfigs.FirstOrDefault(x => x.Id == id);

            Displaysingle display = new Displaysingle();
            display.Id = model.Id;
            display.Title = model.Title;
            display.Sypnosys = model.Sypnosis;
            // File Size
            var file =  "/Upload/" + model.OriginalVideo;
            var fileactual= _env.WebRootPath + "\\Upload\\" + model.OriginalVideo;
            display.Size = Getsize(fileactual);
            display.Duration = Timeduration(fileactual);
            if (a == 1)
            {
                file = "/Converted/" + model.LowQuality;
                var fileactual1 = _env.WebRootPath + "\\Converted\\" + model.LowQuality;
                display.Resolution = "352*240";
                display.Size = Getsize(fileactual1);
            }
            else if (a == 2)
            {
                file = "/Converted/" + model.MediumQuality;
                var fileactual1 = _env.WebRootPath + "\\Converted\\" + model.MediumQuality;
                display.Resolution = "480*360";
                display.Size = Getsize(fileactual1);
            }
            else if (a == 3)
            {
                file = "/Converted/" + model.HighQuality;
                var fileactual1 = _env.WebRootPath + "\\Converted\\" + model.HighQuality;
                display.Resolution = "640*480";
                display.Size = Getsize(fileactual1);
            }
            else if (a == 4)
            {
                file = "/Converted/" + model.VeryHighQuality;
                var fileactual1 = _env.WebRootPath + "\\Converted\\" + model.VeryHighQuality;
                display.Resolution = "1280*720";
                display.Size = Getsize(fileactual1);
            }
            display.Video = file;

            return display;
        }
        public string Timeduration(string file)
        {
            var inputFile = new MediaFile { Filename = file/*"D:\\Projects\\Kleoui\\Sagar\\Final\\Final\\Final\\wwwroot\\ck0urxb4.kl0.mp4"*/ };

            using (var engine = new Engine())
                engine.GetMetadata(inputFile);
            var durationOfMediaFile = inputFile.Metadata.Duration.TotalMilliseconds;
            TimeSpan t = TimeSpan.FromMilliseconds(durationOfMediaFile);

            String time = String.Empty;
            if (t.Hours < 1)
                time = t.Minutes.ToString() + " minutes " + t.Seconds.ToString() + " Seconds";
            else
                time = t.Hours.ToString() + " hours " + t.Minutes.ToString() + " minutes " + t.Seconds.ToString() + " Seconds";

            return  time;
        }
   

    }
    public class Displaysingle
    {
        public int Id { get; set; }
        public string  Video { get; set; }
        public string Resolution { get; set; }
        public string Size { get; set; }
        public string Duration { get; set; }
        public string Title { get; set; }
        public string Sypnosys { get; set; }

    }
}

Views/Listing/Display.cshtml
@*@model NotFinal.Controllers.Displaysingle

@{
    ViewData["Title"] = "Display";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Display</h1>

<div>
    <h4>VideoConfig</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
           <video src="@Model.Video" width="300" height="200" controls loop />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resolution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resolution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MediumQuality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MediumQuality)
       
    </dl>
</div>*@
@model NotFinal.Controllers.Displaysingle

@{
    ViewData["Title"] = "Display";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <title>Hello, world!</title>
    <style>
        .top-nav ul {
            padding: 0;
            list-style: none;
            display: flex;
            justify-content: flex-end;
            margin: 0 0 5px 0;
        }

            .top-nav ul li a {
                font-size: 16px;
                font-weight: 500;
                color: gray !important;
                margin: 0 0 0 30px;
                text-decoration: none;
            }

                .top-nav ul li a.active {
                    color: #0067ef !important;
                }

        .video_png {
            width: 100%;
        }

        .fullpage-div.new___data ul.create_ul {
            background: #137e90;
            padding: 10px 15px !important;
            margin: 0;
            list-style: none;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
        }


        .fullpage-div.new___data .create_ul li p {
            font-size: 16px;
            font-weight: bold;
            color: #fff;
            margin: 0;
        }

        .fullpage-div.new___data {
            margin-top: 15px;
            margin-bottom: 15px;
            border: 1px solid #dddddd;
            border-radius: 6px
        }

        .data-under-all-p1 {
            font-size: 14px;
            margin: 0 0 15px 0;
        }

        .data-under-all-p {
            font-size: 14px;
            margin: 0 0 15px 0;
        }

            .data-under-all-p a {
                background: #30272a;
                color: #fff;
                text-decoration: none;
                padding: 3px 7px;
                border-radius: 5px;
                margin-left: 7px;
            }

        .data-under-all {
            padding: 30px 30px 15px 30px;
        }

        .grid-custom ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
        }

            .grid-custom ul li {
                border: 1px solid #dddddd;
                padding: 15px;
                width: 24%;
                margin: 0 0 15px 0;
            }

        .grid_div_1 {
            background: #137e90;
            height: 60px;
            width: 60px;
            text-align: center;
            line-height: 60px;
            border-radius: 6px;
            font-size: 25px;
            color: #fff;
            margin-right: 10px;
        }

        .duration-p {
            font-size: 14px;
            margin: 0 0 0px 0;
        }

        .duration-p1 {
            font-size: 14px;
            font-weight: bold;
            margin: 0;
        }

        .grid_div {
            display: flex;
            align-items: center;
            justify-content: flex-start;
            width: 100%;
        }


        /*media(max-width: 991px) {
            .grid-custom ul li {
                width: 32%;
            }
        }

        media(max-width: 767px) {
            .grid-custom ul li {
                width: 100%;
            }

            .data-under-all-p a {
                display: block;
                margin: 0;
            }

            .data-under-all {
                padding: 15px 15px 0px 15px;
            }
        }*/
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="top-nav">
                    <ul>
                        <li><a class="active" href="">Home</a></li>
                        <li><a href="">Video Management</a></li>
                        <li><a href="">Creat Video</a></li>
                    </ul>
                </div>
                <p type="text" id="TEXT"  style="display:none;" >@Model.Id</p>
                <div class="video-sec">
                    <video id="videoplayer" src="@Model.Video" width="1270" height="710" controls loop></video>
                    <select class="form-control" id="Quality" name="QualityDropDown" >
                        <option>Original</option> 
                        <option value="250p">250p</option> 
                        <option>360p</option> 
                        <option>480p</option> 
                        <option>720p</option> 
                    </select>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="fullpage-div new___data">
                    <ul class="create_ul">
                        <li>
                            <p id="Title">@Model.Title</p>
                        </li>
                    </ul>
                    <div class="data-under-all">
                        <p class="data-under-all-p1" id="Sypnosys">@Model.Sypnosys</p>
                        <!--<p class="data-under-all-p">
                            Video Management <a href="">Video Management Video Management</a>
                        </p>
                        <p class="data-under-all-p">
                            Video Management <a href="">Video Management Video Management</a>
                        </p>-->
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="grid-custom">
                    <ul>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-gear"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1" id="Duration">@Model.Duration</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1 yellow">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">File Size</p>
                                    <p class="duration-p1" id="Size">@Model.Size</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Resolutoin</p>
                                    <p class="duration-p1" id="Resolution">@Model.Resolution</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1" id="Duration">@Model.Duration</p>
                                </div>
                            </div>
                        </li>
                        <!--<li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1">1 min 40sec</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1">1 min 40sec</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1">1 min 40sec</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="grid_div">
                                <div class="grid_div_1">
                                    <i class="fa-solid fa-circle-play"></i>
                                </div>
                                <div class="grid_div_2">
                                    <p class="duration-p">Video Duration</p>
                                    <p class="duration-p1">1 min 40sec</p>
                                </div>
                            </div>
                        </li>-->
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts
{
    <script>
    $("#Quality").change(function ()
    {
        debugger;
    if($("#Quality").val()=="Original")
    {
        changedata(0);
    }if($("#Quality").val()=="250p")
    {
        changedata(1);
    }if($("#Quality").val()=="360p")
    {
        changedata(2);
    }if($("#Quality").val()=="480p")
    {
        changedata(3);
    }if($("#Quality").val()=="720p")
    {
        changedata(4);
    }
    });
    function changedata(b){
        debugger;
        var dara = $("#TEXT").val();
        $.ajax({
            type:"Post",
            data:{id:$("#TEXT").val(),a:b},

            url:"/Listing/fileinfo",

            success:function(response)
            {
                $("#videoplayer").attr('src',response.Video);
                $("#Title").text=response.Title;
                $("#Sypnosys").text=response.Sypnosys;
                $("#Duration").text=response.Duration;
                $("#Size").text=response.Size;
                $("#Resolution").text=response.Resolution;
            }

        });
    }
</script>
}

Views/Listing/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<NotFinal.Models.VideoConfig>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

<style>
        .top-nav ul {
            padding: 0;
            list-style: none;
            display: flex;
            justify-content: flex-end;
            margin: 0 0 5px 0;
        }

            .top-nav ul li a {
                font-size: 16px;
                font-weight: 500;
                color: gray !important;
                margin: 0 0 0 30px;
                text-decoration: none;
            }

        .fullpage-div {
            border: 1px solid #dddddd;
            border-radius: 6px;
        }

        .create_ul li p {
            font-size: 16px;
            font-weight: bold;
            color: #fff;
            margin: 0;
        }

        .create_ul {
            background: #33393d;
            padding: 10px 15px !important;
            margin: 0;
            list-style: none;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .create-bt {
            font-weight: 600;
            background: #0067ef;
            border: none;
            color: #fff;
            border-radius: 6px;
            font-size: 14px;
            height: 40px;
            padding: 0 15px;
            line-height: 40px;
        }

        .dummy-img {
            max-width: 120px;
        }

        .table-custom table thead tr th {
            font-size: 14px;
            font-weight: bold;
            padding: 15px 30px;
            border-bottom: 1px solid #dddddd;
        }

        .table-custom table {
            width: 100%;
        }

            .table-custom table tbody tr td {
                font-size: 14px;
                font-weight: normal;
                padding: 15px 30px;
                border-bottom: 1px solid #dddddd;
                vertical-align: top;
            }

        .i-tg ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
            justify-content: flex-end;
        }

        .pera__1 {
            font-size: 20px;
            font-weight: bold;
            margin: 0 0 5px 0;
        }

        .pera__2 {
            font-size: 14px;
            margin: auto;
        }

        .top-nav ul li a.active {
            color: #0067ef !important;
        }

        .i-tg li i {
            height: 30px;
            width: 30px;
            text-align: center;
            line-height: 30px;
            margin: 0 0 0 10px;
            border-radius: 5px;
            color: #fff;
            font-size: 14px;
            cursor: pointer;
        }

        .i-tg ul i.fa-solid.fa-info {
            background: #0067ef;
        }

        .i-tg li i.fa-solid.fa-pen-to-square {
            background: #0796b7;
        }

        .i-tg li i.fa-solid.fa-trash-can {
            background: #d13937;
        }

        .table-custom table tbody tr:last-child td {
            border: none;
        }

    /*            media(max-width: 991px) {
                    .table-custom {
                        overflow: auto;
                    }

                    .table-custom table {
                        min-width: 670px;
                    }
                }*/
</style>

<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="top-nav">
                    <ul>
                        <li><a class="active" href="">Home</a></li>
                        <li><a href="">Video Management</a></li>
                        <li><a href="">Creat Video</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="fullpage-div">
                    <ul class="create_ul">
                        <li>
                            <p>List of Video</p>
                        </li>
                        <li><button class="create-bt" onclick="location.href='@Url.Action("AddOriginal", "Upload")'"><i class="fa-solid fa-plus"></i> Create</button></li>
                    </ul>
                    <div class="table-custom">
                        <table>
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>@Html.DisplayNameFor(model => model.Title)</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td><video id="videoplayer" src="@item.OriginalVideo" width="300" height="200" controls loop></td>
                                        <td>
                                            <p class="pera__1"><label>@item.Title</label></p>
                                            <p class="pera__2">Created By : <b>@item.CreatedBy</b></p>
                                            <p class="pera__2">Date : <b>@item.CreatedDate</b></p>
                                            <p class="pera__2">Duration : <b>@item.Duration</b></p>
                                            @*<p class="pera__2">Processed In : <b>hello</b></p>*@
                                        </td>
                                        <td>
                                            <div class="i-tg">
                                                <ul>
                                                    <li onclick="location.href='@Url.Action("Display", "Listing",new{id=@item.Id})'"> <i class="fa-solid fa-info" ></i></li>
                                                    @*<li><i class="fa-solid fa-pen-to-square"></i></li>*@
                                                    <li onclick="DeleteData(@item.Id);"><i class="fa-solid fa-trash-can"></i></li>
                                                    <input type="hidden" id="VideoId" value="@item.Id" />
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OriginalVideo)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <label>@item.Title</label>
            </td>
            <td>
                <video id="videoplayer" src="@item.OriginalVideo" width="300" height="200" controls loop></video>
            </td>
        </tr>
    }
</table>*@

<script type="text/javascript">

    function DeleteData(Id) {
        debugger;
        if (Id != "") {

            var isconfirmed = confirm("Are you sure to delete this user?");
            debugger;
            if (isconfirmed) {
                debugger;
                $.ajax({
                    type: "POST",
                    @*contentType: "application/json; charset=utf-8",*@
                    url: "@Url.Action("DeleteVideoData", "Listing")",
                    data: { Id : Id },
                    dataType: "json",
                    success: function(data) {
                        debugger;
                        if (data == 1) {
                            alert("Record deleted successfully.");
                            window.location.reload();
                        }
                        else {
                            alert("Error in deleting records.");
                        }

                    },
                    error: function(xhr) {
                    }
                });
            }
        }
    }


</script>